### ISSUE TITLE
A few missing emoji after updating to 3.0

### ISSUE THREAD

**Issue by connorshea** [jonathanwiesel/gemojione#26]
- `heart_tip`: https://gitlab.com/gitlab-org/gitlab-ce/issues/18343#note_12637818
- `light_check_mark`: https://gitlab.com/gitlab-org/gitlab-ce/issues/17575#note_12626947

Probably others, I'll update if I see any more.

**Comment by jonathanwiesel** [comment]
You're right @connorshea.

The following definitions were removed on v3 because they aren't really emoji. I mistakenly thought I never released a version with those (unfortunately it seems I did and never realised it until now) and therefore introduced a huge breaking change without commenting it:

```
airplane_northeast
airplane_small_up
anger_left
ascending_notes
ballot_box_check
ballot_box_x
ballot_x
book2
bouquet2
boys_symbol
bullhorn
bullhorn_waves
calculator
cancellation_x
cartridge
celtic_cross
clockwise_arrows
computer_old
cross_heavy
cross_white
crossbones
descending_notes
desktop_window
document
document_text
envelope_back
envelope_flying
envelope_stamped
envelope_stamped_pen
finger_pointing_down
finger_pointing_down2
finger_pointing_left
finger_pointing_right
finger_pointing_up
fire_engine_oncoming
flip_phone
floppy_black
floppy_white
folder
folder_open
frame_tiles
frame_x
girls_symbol
hand_splayed_reverse
hand_victory
hard_disk
heart_tip
info
jet_up
keyboard_mouse
keyboard_with_jacks
keycap_ten
left_receiver
left_writing_hand
light_check_mark
lips2
mood_bubble
mood_bubble_lightning
mood_lightning
mouse_one
network
note
note_empty
notepad
notepad_empty
optical_disk
page
pages
pencil3
pennant_black
pennant_white
piracy
prohibited
pushpin_black
right_speaker
right_speaker_one
right_speaker_three
ringing_bell
rosette_black
speech_left
speech_right
speech_three
speech_two
stereo
stock_chart
telephone_black
telephone_white
thought_left
thought_right
thumbs_down_reverse
thumbs_up_reverse
train_diesel
triangle_round
turned_ok_hand
wired_keyboard
```

From all of those 
- `keycap_ten` is just `ten`.
- `speech_left` should be brought back because it is an actual emoji (http://emojipedia.org/emoji/%F0%9F%97%A8/).

The rest I should put them in the changelog as a breaking change so this doesn't happen to anyone else upgrading the gem.

@connorshea your thoughts?

**Comment by connorshea** [comment]
@jonathanwiesel sounds good to me, ideally we'd have a migration for this or something, but that wouldn't be your job :)

**Comment by jonathanwiesel** [comment]
@connorshea very well, I'll update the changelog and add the missing emoji when I have some time. If I can help in something on your end you know where to find me ;).
